#!/usr/bin/env python3
"""Render gemi_consolidated_model_2025a_2030e.xlsx to markdown, and emit the
machine-readable Q2 2026 prediction record.

The consolidated workbook stores values rather than formulas, so no
recalculation is needed. The markdown render exists so the model is readable on
GitHub and by an AI assistant with no spreadsheet engine.

Outputs:
  CONSOLIDATED_MODEL_TABLES.md   every sheet as markdown tables
  data/q2_2026_prediction.json   the locked Q2 forecast, for scoring after the print

Usage: python3 render_consolidated_model.py
"""

import json
import shutil
import subprocess
import tempfile
from pathlib import Path

from openpyxl import load_workbook

ROOT = Path(__file__).resolve().parent
XLSX = ROOT / "gemi_consolidated_model_2025a_2030e.xlsx"
ANNUAL = ROOT / "GEMI_simple_model_2026-07-30.xlsx"
OUT_MD = ROOT / "CONSOLIDATED_MODEL_TABLES.md"
OUT_ANNUAL_MD = ROOT / "ANNUAL_MODEL_TABLES.md"
OUT_JSON = ROOT / "data" / "q2_2026_prediction.json"

# Rows on the bridge sheet that make up the scored forecast, keyed by label.
SCORED = [
    "Total Revenue",
    "EPS ex-Crypto Marks",
    "Net Revenue",
    "Transaction Revenue",
    "Exchange Revenue",
    "Prediction Revenue",
    "OTC Revenue",
    "Service Revenue",
    "GAAP Opex",
    "Operating Income",
    "Net Loss ex-Crypto Marks",
    "Diluted Shares (M)",
]


def fmt(cell):
    v = cell.value
    if v is None:
        return ""
    if isinstance(v, bool) or not isinstance(v, (int, float)):
        return str(v).replace("|", "\\|").replace("\n", " ")
    nf = cell.number_format or ""
    if "%" in nf:
        return f"{v * 100:,.1f}%"
    if nf.startswith("$"):
        return f"${v:,.2f}"
    if float(v).is_integer() and abs(v) < 3000 and "," not in nf:
        return str(int(v))
    if float(v).is_integer():
        return f"{int(v):,}"
    return f"{v:,.2f}" if abs(v) < 1000 else f"{v:,.1f}"


def render():
    wb = load_workbook(XLSX, data_only=True)
    lines = [
        "# GEMI Consolidated Model — rendered tables",
        "",
        "> **RETAINED FOR THE Q2 BRIDGE ONLY — as of 29 July 2026.** The `Q2-26 Bridge vs",
        "> Consensus` sheet below is the source of the locked Q2 2026 call. The `Model` sheet is",
        "> **superseded** by `GEMI_simple_model_2026-07-30.xlsx`; do not quote its annual figures.",
        "> The `Prediction Market Comps` sheet carries a known counting error in its July row and",
        "> should not be quoted at all — see D1 in `REVIEW_ARTEMIS_MODEL.md`.",
        "",
        "Plain-text rendering of every sheet in `gemi_consolidated_model_2025a_2030e.xlsx`.",
        "Generated by `render_consolidated_model.py`; do not hand-edit.",
        "This exists so the model can be read on GitHub or by an AI assistant without Excel.",
        "",
        "The workbook stores values, not formulas, so nothing here is a recalculation.",
        "The `KEY MODEL RELATIONSHIPS` block on the `Model` sheet documents how each line",
        "was derived.",
        "",
    ]
    for ws in wb.worksheets:
        lines += [f"## {ws.title}", ""]
        grid = []
        for r in range(1, ws.max_row + 1):
            vals = [fmt(ws.cell(r, c)) for c in range(1, ws.max_column + 1)]
            while vals and vals[-1] == "":
                vals.pop()
            grid.append(vals)
        i = 0
        while i < len(grid):
            if not grid[i]:
                i += 1
                continue
            block = []
            while i < len(grid) and grid[i]:
                block.append(grid[i])
                i += 1
            width = max(len(v) for v in block)
            if width == 1:
                for row in block:
                    lines += [row[0], ""]
                continue
            for j, vals in enumerate(block):
                vals = vals + [""] * (width - len(vals))
                lines.append("| " + " | ".join(vals) + " |")
                if j == 0:
                    lines.append("|" + "|".join(["---"] * width) + "|")
            lines.append("")
    OUT_MD.write_text("\n".join(lines))
    return wb


def emit_prediction(wb):
    ws = wb["Q2-26 Bridge vs Consensus"]
    by_label = {}
    for r in range(1, ws.max_row + 1):
        label = ws.cell(r, 1).value
        if isinstance(label, str):
            by_label[label.strip()] = r

    def cell(row, col):
        v = ws.cell(row, col).value
        return v if isinstance(v, (int, float)) and not isinstance(v, bool) else None

    lines = {}
    for label in SCORED:
        r = by_label.get(label)
        if r is None:
            continue
        lines[label] = {
            "q1_2026_actual": cell(r, 2),
            "q2_2026_forecast": cell(r, 3),
            "q2_2026_consensus": cell(r, 4),
            "actual": None,
            "basis": ws.cell(r, 6).value,
        }

    scen_start = by_label.get("Scenario")
    scenarios = {}
    if scen_start:
        for r in range(scen_start + 1, scen_start + 4):
            name = ws.cell(r, 1).value
            if not name:
                continue
            scenarios[str(name).lower()] = {
                "revenue": cell(r, 2),
                "gaap_opex": cell(r, 3),
                "net_loss_ex_marks": cell(r, 4),
                "eps_ex_marks": cell(r, 5),
            }

    payload = {
        "schema": "gemi-quarterly-prediction/1",
        "ticker": "GEMI",
        "quarter": "Q2 2026",
        "period_end": "2026-06-30",
        "expected_report": "August 2026",
        "locked_on": "2026-07-29",
        "price_at_lock": 4.065,
        "status": "OPEN",
        "headline": {
            "total_revenue_usd_m": lines.get("Total Revenue", {}).get("q2_2026_forecast"),
            "eps_ex_crypto_marks_usd": lines.get("EPS ex-Crypto Marks", {}).get("q2_2026_forecast"),
            "consensus_total_revenue_usd_m": lines.get("Total Revenue", {}).get("q2_2026_consensus"),
            "consensus_eps_usd": lines.get("EPS ex-Crypto Marks", {}).get("q2_2026_consensus"),
        },
        "scoring_rules": {
            "revenue_hit_band_usd_m": 1.0,
            "eps_hit_band_usd": 0.03,
            "note": (
                "Score EPS against a figure that excludes crypto mark-to-market. Reported GAAP EPS "
                "includes marks and is not forecastable: Q1 2026 carried a -$101M gross swing on crypto "
                "assets partly offset by +$90M on crypto loans payable, netting about -$0.09 per share. "
                "A GAAP miss driven by marks is not a model miss."
            ),
        },
        "lines": lines,
        "scenarios": scenarios,
        "verify_against": [
            "https://investors.gemini.com/news-releases",
            "https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0002055592&type=10-Q",
        ],
        "source_workbook": XLSX.name,
    }
    OUT_JSON.write_text(json.dumps(payload, indent=2) + "\n")
    return payload


def recalculated_copy(src):
    """Return a path to a recalculated COPY of src, or None.

    The annual workbook ships without cached formula results, so every computed
    cell reads back empty. LibreOffice is used to evaluate them. It always works
    on a copy in a temp directory: the author's workbook is never modified.
    """
    tmp = Path(tempfile.mkdtemp(prefix="gemi-recalc-"))
    staged = tmp / src.name
    shutil.copy2(src, staged)
    try:
        subprocess.run(
            ["soffice", "--headless", "--norestore", "--convert-to", "xlsx",
             "--outdir", str(tmp / "out"), str(staged)],
            check=True, capture_output=True, timeout=180,
        )
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired, FileNotFoundError) as e:
        print(f"  WARNING: could not recalculate {src.name} ({type(e).__name__}). "
              f"Computed cells will render blank. Install LibreOffice for a full render.")
        return None
    produced = tmp / "out" / src.name
    return produced if produced.exists() else None


def render_annual():
    """Render the current annual model, recalculating a copy so formula results
    are present. Errors such as #DIV/0! are rendered as-is rather than hidden."""
    if not ANNUAL.exists():
        print(f"  skipped {ANNUAL.name} (not found)")
        return
    source = recalculated_copy(ANNUAL) or ANNUAL
    wb = load_workbook(source, data_only=True)
    lines = [
        "# GEMI Annual Model (2025A-2030E) — rendered tables",
        "",
        "> **CURRENT ANNUAL MODEL — as of 30 July 2026.** Source of truth for every annual and",
        "> valuation figure. Supersedes the annual sheet of the consolidated model. The Q2 2026",
        "> quarterly call still comes from the consolidated model's bridge sheet; see",
        "> `Q2_2026_SCORECARD.md`.",
        "",
        f"Plain-text rendering of every sheet in `{ANNUAL.name}`.",
        "Generated by `render_consolidated_model.py`; do not hand-edit.",
        "",
        "`#DIV/0!` in the 2023 and 2024 columns is expected: GEMI IPO'd in 2025, so there is no",
        "prior-year data for the ratio rows to divide by. Treat those two columns as not",
        "applicable rather than as computed zeros.",
        "",
    ]
    for ws in wb.worksheets:
        lines += [f"## {ws.title}", ""]
        grid = []
        for r in range(1, ws.max_row + 1):
            vals = [fmt(ws.cell(r, c)) for c in range(1, ws.max_column + 1)]
            while vals and vals[-1] == "":
                vals.pop()
            grid.append(vals)
        i = 0
        while i < len(grid):
            if not grid[i]:
                i += 1
                continue
            block = []
            while i < len(grid) and grid[i]:
                block.append(grid[i])
                i += 1
            width = max(len(v) for v in block)
            if width == 1:
                for row in block:
                    lines += [row[0], ""]
                continue
            for j, vals in enumerate(block):
                vals = vals + [""] * (width - len(vals))
                lines.append("| " + " | ".join(vals) + " |")
                if j == 0:
                    lines.append("|" + "|".join(["---"] * width) + "|")
            lines.append("")
    OUT_ANNUAL_MD.write_text("\n".join(lines))
    print(f"  wrote {OUT_ANNUAL_MD.name}")


def main():
    if not XLSX.exists():
        raise SystemExit(f"Missing {XLSX}")
    wb = render()
    render_annual()
    p = emit_prediction(wb)
    h = p["headline"]
    print(f"  wrote {OUT_MD.name}")
    print(f"  wrote {OUT_JSON.relative_to(ROOT)}")
    print(f"\n  Q2 2026 call: revenue ${h['total_revenue_usd_m']}M, EPS ex-marks ${h['eps_ex_crypto_marks_usd']}")
    print(f"  consensus:    revenue ${h['consensus_total_revenue_usd_m']}M, EPS ${h['consensus_eps_usd']}")


if __name__ == "__main__":
    main()
